version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: gulp
    volumes:
      - .:/code
      - /code/node_modules
    ports:
      - "8000:8000"
    depends_on:
      - db
